### ISSUE TITLE
谷歌网盘权限

### ISSUE THREAD

**Issue by ABCDZLG** [nv-dvl/nerfmatch#1]
您好，请问谷歌网盘的数据权限可以开放吗？谢谢
我想要下载下来(因为在我的服务器上的使用gdown没有成功)

**Comment by GrumpyZhou** [comment]
嗨，可以再试一下吗？我换了个位置。

**Comment by ABCDZLG** [comment]
> 嗨，可以再试一下吗？我换了个位置。

抱歉，请问一下，您改动了哪里

**Comment by ABCDZLG** [comment]
> 嗨，可以再试一下吗？我换了个位置。

非常感谢，现在可以了
但是我还是想问一下，为什么使用gdown下载不下来呢？(以前使用gdown下载谷歌网盘也下载不下来，都是去找的谷歌网盘的链接下载的)是gdown本身的问题还是服务器太老(现在我暂时使用英伟达tianxp)？

下面是执行@server-SYS-7048GR-TR:~/nerfmatch-main/data$                  bash download_data.sh  命令发生的错误


Error:

	HTTPSConnectionPool(host='drive.google.com', port=443): Max retries
	exceeded with url: /uc?id=1-gOqAA0-sdiUZmQLRYlGprQdk7ttldfE (Caused by
	NewConnectionError('<urllib3.connection.HTTPSConnection object at
	0x7f02099fb940>: Failed to establish a new connection: [Errno 101]
	Network is unreachable'))

To report issues, please visit https://github.com/wkentaro/gdown/issues.
tar (child): pairs.tar.gz：无法 open: 没有那个文件或目录
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
rm: 无法删除 'pairs.tar.gz': 没有那个文件或目录
Error:

	HTTPSConnectionPool(host='drive.google.com', port=443): Max retries
	exceeded with url: /uc?id=1iHwsGwKXZWHxF_o9OMZUnGYKCopO-cKS (Caused by
	NewConnectionError('<urllib3.connection.HTTPSConnection object at
	0x7f6db66fc700>: Failed to establish a new connection: [Errno 101]
	Network is unreachable'))

To report issues, please visit https://github.com/wkentaro/gdown/issues.
tar (child): annotations.tar.gz：无法 open: 没有那个文件或目录
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
rm: 无法删除 'annotations.tar.gz': 没有那个文件或目录
^Z
[1]+  已停止               bash download_data.sh

**Comment by GrumpyZhou** [comment]
你的gdown 是那个版本呢？ 我这边是可以的
```
Name: gdown
Version: 5.2.0
```

**Comment by hidfgidh** [comment]
> 你的gdown 是那个版本呢？ 我这边是可以的
> 
> ```
> Name: gdown
> Version: 5.2.0
> ```

我的版本也是5.2.0，但是在gdown的github的issues里也有很多这种情况发生（链接https://github.com/wkentaro/gdown/issues)问题#367和#358

**Comment by hidfgidh** [comment]
> 你的gdown 是那个版本呢？ 我这边是可以的
> 
> ```
> Name: gdown
> Version: 5.2.0
> ```


我的版本也是5.2.0，但是在gdown的github的issues里也有很多这种情况发生，一下链接下的问题#367和#358，链接https://github.com/wkentaro/gdown/issues

**Comment by ABCDZLG** [comment]
非常感谢作者，我现在知道原因了，大陆境内是没有办法直接用gdown下载谷歌网盘上的内容，除非去国外，所以只能挂梯子访问外网

并且我在服务器上运行您提供的代码，非常遗憾，因为地域和网络的原因，失败了，在代码过程中，是有下载模型的过程，这个过程中需要访问外网，所以最后也是失败的，
我尝试找到代码报错过程中的文件，在huggingface的国内镜像网站 (https://hf-mirror.com) 中是有的，但是我不知道放在哪个文件夹下

再次感谢您出色的工作

**Comment by GrumpyZhou** [comment]
https://huggingface.co/docs/transformers/main/en/installation#cache-setup  这里有些default model cache path.

**Comment by ABCDZLG** [comment]
因为在报错信息中，是要借助urlib3和request库去访问huggingface去下载模型，所以可不可以把那个要访问的网站更换为国内的镜像网站(公用服务器无法安装翻墙软件)，但是那个要访问的外网的具体地址是什么，我在代码文件和所安装的库文件里没有找到那些网址，


请问您可以找到在代码中要修改的网址的位置吗，我想把它换成国内的镜像网站，再重新尝试一下

代码本身没有问题，因为无法连接外网，相关的报错信息全部都是在site-packages/huggingface_hub/file_download.py文件和site-packages/urllib3/util/connection.py文件等，完整的报错信息和    https://github.com/nv-dvl/nerfmatch/issues/4#issue-2619903371    相同（也就是第4个问题#4）
